name: Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest release tag
        id: get_latest_release
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0.0")
          echo "Latest release tag: $latest_tag"
          echo "::set-output name=tag::$latest_tag"

      - name: Generate new release version
        id: generate_new_version
        run: |
          latest_tag="${{ steps.get_latest_release.outputs.tag }}"
          version_numbers=(${latest_tag//./ })
          version_numbers[3]=$((version_numbers[3]+1)) # Increment the last number
          new_version="v${version_numbers[0]}.${version_numbers[1]}.${version_numbers[2]}.${version_numbers[3]}"
          echo "New version: $new_version"
          echo "::set-output name=new_version::$new_version"

      - name: Generate Changelog
        id: generate_changelog
        run: |
          changelog=$(git log --oneline $(git describe --tags --abbrev=0 @^)..@)
          echo "Changelog: $changelog"
          echo "::set-output name=changelog::$changelog"

      - name: Push new tag
        env:
          JAY_GHP_SECRET: ${{ secrets.JAY_GHP_SECRET }}  # Use PAT
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.generate_new_version.outputs.new_version }}
          git push https://x-access-token:${{ secrets.JAY_GHP_SECRET }}@github.com/JayShenkar07/K8-Sample-Python-App-1.git --tags

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate_new_version.outputs.new_version }}
          release_name: "Release ${{ steps.generate_new_version.outputs.new_version }}"
          body: ${{ steps.generate_changelog.outputs.changelog }}
          draft: false
          prerelease: false
